### ISSUE TITLE
qmake path in Makefile

### ISSUE THREAD

**Issue by lucazade** [smclt30p/Rufusl#1]
I'm trying to build Rufusl in Manjaro Linux but qmake path in makefile is wrong.
In Manjaro/Archlinux qmake is located in /usr/bin.

**Comment by smclt30p** [comment]
Rufusl is far from being usable and buildable. This repository is used for developers, if I could I would mark the repository private, but I can't.

**Comment by smclt30p** [comment]
Issue fixed, instead of make run qmake to generate the Makefile, then do make.
